<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ClinicalWorkflowSeeder extends Seeder
{
    public function run()
    {
        $db = \Config\Database::connect();

        $patients = [
            [
                'id'                => 1,
                'hospital_id'       => 1,
                'department_id'     => 2, // ICU
                'uhid'              => 'UHID-HQM-2026-00101',
                'first_name'        => 'Rameshwar',
                'last_name'         => 'Sharma',
                'gender'            => 'male',
                'dob'               => '1968-04-12',
                'age'               => 58,
                'mobile'            => '9876543210',
                'emergency_contact' => '9876543211 (Son - Vivek)',
                'blood_group'       => 'B+',
                'address'           => 'Flat 402, Shanti Heights, Sector 14, New Delhi',
                'abha_number'       => '91-4567-8912-3456',
                'abha_address'      => 'rameshwar.sharma@abdm',
                'abha_status'       => 'verified',
                'admission_status'  => 'admitted_icu',
                'bed_number'        => 'ICU-BED-04',
                'attending_doctor'  => 'Dr. Vikram Malhotra (Critical Care Lead)',
                'admission_date'    => date('Y-m-d H:i:s', strtotime('-2 days')),
                'discharge_date'    => null,
                'created_at'        => date('Y-m-d H:i:s', strtotime('-2 days')),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'id'                => 2,
                'hospital_id'       => 1,
                'department_id'     => 4, // Cardiology
                'uhid'              => 'UHID-HQM-2026-00102',
                'first_name'        => 'Sunita',
                'last_name'         => 'Deshmukh',
                'gender'            => 'female',
                'dob'               => '1975-09-25',
                'age'               => 51,
                'mobile'            => '9811223344',
                'emergency_contact' => '9811223355 (Husband - Alok)',
                'blood_group'       => 'O+',
                'address'           => 'House 12B, Vasant Vihar, New Delhi',
                'abha_number'       => '91-8890-1234-5678',
                'abha_address'      => 'sunita.deshmukh@abdm',
                'abha_status'       => 'verified',
                'admission_status'  => 'pre_op',
                'bed_number'        => 'CARD-WARD-12',
                'attending_doctor'  => 'Dr. Rajesh Nair (Cardiologist)',
                'admission_date'    => date('Y-m-d H:i:s', strtotime('-1 days')),
                'discharge_date'    => null,
                'created_at'        => date('Y-m-d H:i:s', strtotime('-1 days')),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'id'                => 3,
                'hospital_id'       => 1,
                'department_id'     => 3, // OT Complex
                'uhid'              => 'UHID-HQM-2026-00103',
                'first_name'        => 'Mohd.',
                'last_name'         => 'Tariq',
                'gender'            => 'male',
                'dob'               => '1990-02-18',
                'age'               => 36,
                'mobile'            => '9988776655',
                'emergency_contact' => '9988776644 (Brother - Rehan)',
                'blood_group'       => 'A+',
                'address'           => '78 Zakir Nagar, Okhla, New Delhi',
                'abha_number'       => '91-3344-5566-7788',
                'abha_address'      => 'mohd.tariq@abdm',
                'abha_status'       => 'verified',
                'admission_status'  => 'post_op',
                'bed_number'        => 'POST-OP-RECOVERY-02',
                'attending_doctor'  => 'Dr. Priya Nair (General Surgeon)',
                'admission_date'    => date('Y-m-d H:i:s', strtotime('-3 days')),
                'discharge_date'    => null,
                'created_at'        => date('Y-m-d H:i:s', strtotime('-3 days')),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'id'                => 4,
                'hospital_id'       => 1,
                'department_id'     => 1, // Emergency
                'uhid'              => 'UHID-HQM-2026-00104',
                'first_name'        => 'Ananya',
                'last_name'         => 'Chatterjee',
                'gender'            => 'female',
                'dob'               => '1998-11-05',
                'age'               => 28,
                'mobile'            => '9711002233',
                'emergency_contact' => '9711002244 (Mother - Smt. Gita)',
                'blood_group'       => 'AB+',
                'address'           => 'Tower 3, Apt 1104, CR Park, New Delhi',
                'abha_number'       => null,
                'abha_address'      => null,
                'abha_status'       => 'unlinked',
                'admission_status'  => 'registered',
                'bed_number'        => 'EMR-TRIAGE-03',
                'attending_doctor'  => 'Dr. Sunil Verma (Emergency MO)',
                'admission_date'    => date('Y-m-d H:i:s', strtotime('-4 hours')),
                'discharge_date'    => null,
                'created_at'        => date('Y-m-d H:i:s', strtotime('-4 hours')),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
        ];

        $db->table('patients')->emptyTable();
        $db->table('patients')->insertBatch($patients);

        // Seed DPDP Consents for each patient
        $consents = [
            // Patient 1 Consents
            [
                'hospital_id'            => 1,
                'patient_id'             => 1,
                'consent_type'           => 'general_admission',
                'consent_title'          => 'General Inpatient Admission & Clinical Care Consent',
                'purpose_description'    => 'Authorization for routine nursing care, diagnostic monitoring, and intravenous medication under NABH standards.',
                'data_fiduciary'         => 'Hospital Quality Management / Clinical Data Fiduciary',
                'signatory_type'         => 'guardian',
                'signatory_name'         => 'Vivek Sharma (Son)',
                'status'                 => 'granted',
                'granted_at'             => date('Y-m-d H:i:s', strtotime('-2 days')),
                'expiry_date'            => date('Y-m-d', strtotime('+28 days')),
                'digital_signature_hash' => 'SIG-SHA256-A89F12BC9941',
                'verification_otp'       => '8821',
                'ip_address'             => '192.168.1.104',
                'language'               => 'en',
                'witness_name'           => 'Sister Lini (ICU Incharge)',
                'created_at'             => date('Y-m-d H:i:s', strtotime('-2 days')),
                'updated_at'             => date('Y-m-d H:i:s', strtotime('-2 days')),
            ],
            [
                'hospital_id'            => 1,
                'patient_id'             => 1,
                'consent_type'           => 'abdm_data_sharing',
                'consent_title'          => 'DPDP Act 2023 & ABDM Health Records Data Sharing Consent',
                'purpose_description'    => 'Informed electronic consent for linking diagnostic telemetry reports to ABHA (91-4567-8912-3456) for longitudinal clinical care.',
                'data_fiduciary'         => 'National Health Authority (NHA) & Hospital Quality Management',
                'signatory_type'         => 'guardian',
                'signatory_name'         => 'Vivek Sharma (Son)',
                'status'                 => 'granted',
                'granted_at'             => date('Y-m-d H:i:s', strtotime('-2 days')),
                'expiry_date'            => date('Y-m-d', strtotime('+365 days')),
                'digital_signature_hash' => 'SIG-DPDP-EE4590A11029',
                'verification_otp'       => '4590',
                'ip_address'             => '192.168.1.104',
                'language'               => 'en',
                'witness_name'           => 'Dr. Ananya Sen (Quality Lead)',
                'created_at'             => date('Y-m-d H:i:s', strtotime('-2 days')),
                'updated_at'             => date('Y-m-d H:i:s', strtotime('-2 days')),
            ],
            [
                'hospital_id'            => 1,
                'patient_id'             => 1,
                'consent_type'           => 'icu_invasive_care',
                'consent_title'          => 'Invasive Mechanical Ventilation & Central Line Consent',
                'purpose_description'    => 'Informed consent for endotracheal intubation, arterial line insertion, and ICU invasive monitoring.',
                'data_fiduciary'         => 'Hospital Quality Management ICU Desk',
                'signatory_type'         => 'guardian',
                'signatory_name'         => 'Vivek Sharma (Son)',
                'status'                 => 'granted',
                'granted_at'             => date('Y-m-d H:i:s', strtotime('-2 days')),
                'expiry_date'            => date('Y-m-d', strtotime('+15 days')),
                'digital_signature_hash' => 'SIG-ICU-7721C004F981',
                'verification_otp'       => '9912',
                'ip_address'             => '192.168.1.104',
                'language'               => 'en',
                'witness_name'           => 'Dr. Vikram Malhotra',
                'created_at'             => date('Y-m-d H:i:s', strtotime('-2 days')),
                'updated_at'             => date('Y-m-d H:i:s', strtotime('-2 days')),
            ],

            // Patient 2 Consents
            [
                'hospital_id'            => 1,
                'patient_id'             => 2,
                'consent_type'           => 'general_admission',
                'consent_title'          => 'General Inpatient Admission & Clinical Care Consent',
                'purpose_description'    => 'Authorization for cardiac monitoring, continuous ECG telemetry, and medication protocols.',
                'data_fiduciary'         => 'Hospital Quality Management / Clinical Data Fiduciary',
                'signatory_type'         => 'patient',
                'signatory_name'         => 'Sunita Deshmukh',
                'status'                 => 'granted',
                'granted_at'             => date('Y-m-d H:i:s', strtotime('-1 days')),
                'expiry_date'            => date('Y-m-d', strtotime('+30 days')),
                'digital_signature_hash' => 'SIG-SHA256-441098AA3312',
                'verification_otp'       => '3310',
                'ip_address'             => '192.168.1.112',
                'language'               => 'hi',
                'witness_name'           => 'Staff Nurse Sarita',
                'created_at'             => date('Y-m-d H:i:s', strtotime('-1 days')),
                'updated_at'             => date('Y-m-d H:i:s', strtotime('-1 days')),
            ],
            [
                'hospital_id'            => 1,
                'patient_id'             => 2,
                'consent_type'           => 'surgery_anesthesia',
                'consent_title'          => 'Coronary Angiography & Possible Angioplasty (PTCA) Consent',
                'purpose_description'    => 'Informed consent for femoral/radial arterial puncture, contrast dye administration, coronary balloon angioplasty, and stent deployment.',
                'data_fiduciary'         => 'Hospital Quality Management Cath Lab',
                'signatory_type'         => 'patient',
                'signatory_name'         => 'Sunita Deshmukh',
                'status'                 => 'granted',
                'granted_at'             => date('Y-m-d H:i:s', strtotime('-4 hours')),
                'expiry_date'            => date('Y-m-d', strtotime('+7 days')),
                'digital_signature_hash' => 'SIG-CATH-558911C4402',
                'verification_otp'       => '5589',
                'ip_address'             => '192.168.1.112',
                'language'               => 'en',
                'witness_name'           => 'Dr. Rajesh Nair (Interventional Cardiologist)',
                'created_at'             => date('Y-m-d H:i:s', strtotime('-4 hours')),
                'updated_at'             => date('Y-m-d H:i:s', strtotime('-4 hours')),
            ],
            [
                'hospital_id'            => 1,
                'patient_id'             => 2,
                'consent_type'           => 'abdm_data_sharing',
                'consent_title'          => 'DPDP Act 2023 & ABDM Health Records Data Sharing Consent',
                'purpose_description'    => 'Electronic health data consent under DPDP Act 2023 for ABDM M3 certified repository synchronization.',
                'data_fiduciary'         => 'Hospital Quality Management',
                'signatory_type'         => 'patient',
                'signatory_name'         => 'Sunita Deshmukh',
                'status'                 => 'granted',
                'granted_at'             => date('Y-m-d H:i:s', strtotime('-1 days')),
                'expiry_date'            => date('Y-m-d', strtotime('+365 days')),
                'digital_signature_hash' => 'SIG-DPDP-887711BC99',
                'verification_otp'       => '8877',
                'ip_address'             => '192.168.1.112',
                'language'               => 'en',
                'witness_name'           => 'Quality Desk Officer',
                'created_at'             => date('Y-m-d H:i:s', strtotime('-1 days')),
                'updated_at'             => date('Y-m-d H:i:s', strtotime('-1 days')),
            ],

            // Patient 3 Consents
            [
                'hospital_id'            => 1,
                'patient_id'             => 3,
                'consent_type'           => 'general_admission',
                'consent_title'          => 'General Inpatient Admission & Clinical Care Consent',
                'purpose_description'    => 'Standard admission authorization for laparoscopic appendectomy surgical care.',
                'data_fiduciary'         => 'Hospital Quality Management / Clinical Data Fiduciary',
                'signatory_type'         => 'patient',
                'signatory_name'         => 'Mohd. Tariq',
                'status'                 => 'granted',
                'granted_at'             => date('Y-m-d H:i:s', strtotime('-3 days')),
                'expiry_date'            => date('Y-m-d', strtotime('+30 days')),
                'digital_signature_hash' => 'SIG-SHA256-990011FF223',
                'verification_otp'       => '1199',
                'ip_address'             => '192.168.1.115',
                'language'               => 'en',
                'witness_name'           => 'OT Staff Nurse',
                'created_at'             => date('Y-m-d H:i:s', strtotime('-3 days')),
                'updated_at'             => date('Y-m-d H:i:s', strtotime('-3 days')),
            ],
            [
                'hospital_id'            => 1,
                'patient_id'             => 3,
                'consent_type'           => 'surgery_anesthesia',
                'consent_title'          => 'Laparoscopic Surgery & General Anesthesia Consent',
                'purpose_description'    => 'Informed consent for Laparoscopic Appendectomy under General Endotracheal Anesthesia.',
                'data_fiduciary'         => 'Hospital Quality Management Surgery Desk',
                'signatory_type'         => 'patient',
                'signatory_name'         => 'Mohd. Tariq',
                'status'                 => 'granted',
                'granted_at'             => date('Y-m-d H:i:s', strtotime('-3 days')),
                'expiry_date'            => date('Y-m-d', strtotime('+7 days')),
                'digital_signature_hash' => 'SIG-SURG-774411AA00',
                'verification_otp'       => '7744',
                'ip_address'             => '192.168.1.115',
                'language'               => 'en',
                'witness_name'           => 'Dr. Priya Nair',
                'created_at'             => date('Y-m-d H:i:s', strtotime('-3 days')),
                'updated_at'             => date('Y-m-d H:i:s', strtotime('-3 days')),
            ],

            // Patient 4 Consents (Draft / Pending)
            [
                'hospital_id'            => 1,
                'patient_id'             => 4,
                'consent_type'           => 'general_admission',
                'consent_title'          => 'General Inpatient Admission & Emergency Triage Consent',
                'purpose_description'    => 'Emergency department evaluation, blood sampling, and continuous vitals telemetry.',
                'data_fiduciary'         => 'Hospital Quality Management',
                'signatory_type'         => 'patient',
                'signatory_name'         => 'Ananya Chatterjee',
                'status'                 => 'draft',
                'granted_at'             => null,
                'expiry_date'            => null,
                'digital_signature_hash' => null,
                'verification_otp'       => null,
                'ip_address'             => null,
                'language'               => 'en',
                'witness_name'           => null,
                'created_at'             => date('Y-m-d H:i:s', strtotime('-4 hours')),
                'updated_at'             => date('Y-m-d H:i:s', strtotime('-4 hours')),
            ],
            [
                'hospital_id'            => 1,
                'patient_id'             => 4,
                'consent_type'           => 'abdm_data_sharing',
                'consent_title'          => 'DPDP Act 2023 & ABDM Health Records Data Sharing Consent',
                'purpose_description'    => 'Consent to link emergency diagnostic reports with Ayushman Bharat Digital Mission (ABDM).',
                'data_fiduciary'         => 'Hospital Quality Management',
                'signatory_type'         => 'patient',
                'signatory_name'         => 'Ananya Chatterjee',
                'status'                 => 'draft',
                'granted_at'             => null,
                'expiry_date'            => null,
                'digital_signature_hash' => null,
                'verification_otp'       => null,
                'ip_address'             => null,
                'language'               => 'en',
                'witness_name'           => null,
                'created_at'             => date('Y-m-d H:i:s', strtotime('-4 hours')),
                'updated_at'             => date('Y-m-d H:i:s', strtotime('-4 hours')),
            ],
        ];

        $db->table('dpdp_consents')->emptyTable();
        $db->table('dpdp_consents')->insertBatch($consents);

        // Seed Patient Workflow Steps
        $workflowModel = new \App\Models\PatientWorkflowStepModel();
        $db->table('patient_workflow_steps')->emptyTable();

        foreach ([1, 2, 3, 4] as $pId) {
            $workflowModel->initStepsForPatient(1, $pId);
        }
    }
}
